train_dataset:
  dataset:
    name: paired-nm-folders
  wrapper:
    name: sr-implicit-paired-nm
    args:
      sample_q: 512
  batch_size: 16

val_dataset:
  dataset:
    name: paired-nm-folders
  wrapper:
    name: sr-implicit-paired-test
    args:
      scale: none
  batch_size: 1

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}

model:
  name: liif-nm
  args:
    encoder_spec:
      name: edsr-nm
      args:
        w_split_ratio: none
        use_pe: false
    imnet_spec:
      name: mlp
      args:
        out_dim: 3
        hidden_list: [384, 384, 384, 384]

train_variable_feat_extractor: true
use_auxiliary_train_step: true

optimizer:
  name: adam
  args:
    lr: 1.e-4
epoch_max: 50
multi_step_lr:
  milestones: [25, 200]
  gamma: 0.1

epoch_val: 1
epoch_save: 10
